### ISSUE TITLE
[Bounty]API使用问题汇总

### ISSUE THREAD

**Issue by micah13433** [Rovak/wallet-web#105]
[Bounty]API使用问题汇总
1.getBlockByNumToView接口获取的区块 WitnessId 一直为0；
  WitnessAddress() 得到的地址还是类似 A0A0621B42F2FDEF84EA993F130A756CC386F7F5E2 的旧格式。

2.Block和Transaction缺乏大量应用接口，而这些是区块链基本的查询要求：
  分页查询Block，Transaction集合；
  Transaction支持按userid或类型查询所有关联交易记录。

**Comment by Rovak** [comment]
This has been fixed

**Comment by tronmarcus** [comment]
Hi, @micah13433 ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by marcusyanghe** [comment]
Hi, @micah13433 ,
(Just in case, my last comment of the same content may not be shown to you, since my prev account was flagged by GitHub spam system, so I am using this account to repost the same comment)
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
