### ISSUE TITLE
Account Refresh -> Logout

### ISSUE THREAD

**Issue by bondibox** [Rovak/wallet-web#176]
If you navigate to your account page and then reload the page, it logs you out. If you reload the site from any other page it keeps you logged in.

**Comment by lazarovicedo** [comment]
fixed on PR #153

**Comment by tronmarcus** [comment]
Hi, @bondibox ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by marcusyanghe** [comment]
Hi, @bondibox ,
(Just in case, my last comment of the same content may not be shown to you, since my prev account was flagged by GitHub spam system, so I am using this account to repost the same comment)
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network  so we can deliver the TRX on time. 
Thanks,
Marcus Yang
